const DEFAULT_KEYBINDINGS = {
  // ナビゲーション
  focusNext:    'ArrowDown',
  focusPrev:    'ArrowUp',
  openPost:     'Enter',
  // 投稿アクション
  like:         'l',
  repost:       'r',
  quoteRepost:  'q',
  bookmark:     'b',
  reply:        '@',
  openProfile:  'p',
  openQuoted:   'o',
  // グローバル
  newPost:      'n',
  focusSearch:  '/',
  toggleHelp:   '?',
  tabPrev:      '[',
  tabNext:      ']',
  tabOuterPrev: '{',
  tabOuterNext: '}',
  // ページ移動（数字キー）
  navHome:      '1',
  navSearch:    '2',
  navNotif:     '3',
  navMessages:  '4',
  navBookmarks: '5',
  navProfile:   '6',
  navSettings:  '7',
};

const ACTION_LABELS = {
  focusNext:    '次の投稿へ移動',
  focusPrev:    '前の投稿へ移動',
  openPost:     '投稿を開く',
  like:         'いいね',
  repost:       'リポスト（直接）',
  quoteRepost:  '引用リポスト',
  bookmark:     'ブックマーク',
  reply:        'リプライ',
  openProfile:  '投稿者プロフィールを開く',
  openQuoted:   '引用元投稿を開く',
  newPost:      '新規投稿',
  focusSearch:  '検索欄にフォーカス',
  toggleHelp:   'ヘルプの表示/非表示',
  tabPrev:      '前の内側タブへ',
  tabNext:      '次の内側タブへ',
  tabOuterPrev: '前の外側タブへ',
  tabOuterNext: '次の外側タブへ',
  navHome:      'ホームへ移動',
  navSearch:    '検索ページへ移動',
  navNotif:     '通知へ移動',
  navMessages:  'メッセージへ移動',
  navBookmarks: 'ブックマークへ移動',
  navProfile:   '自分のプロフィールへ移動',
  navSettings:  '設定へ移動',
};

// ヘルプオーバーレイのセクション定義
const HELP_SECTIONS = [
  { title: 'ナビゲーション',  actions: ['focusNext', 'focusPrev', 'openPost'] },
  { title: '投稿アクション', actions: ['like', 'repost', 'quoteRepost', 'bookmark', 'reply', 'openProfile', 'openQuoted'] },
  { title: 'グローバル',     actions: ['newPost', 'focusSearch', 'toggleHelp', 'tabPrev', 'tabNext', 'tabOuterPrev', 'tabOuterNext'] },
  { title: 'ページ移動',     actions: ['navHome', 'navSearch', 'navNotif', 'navMessages', 'navBookmarks', 'navProfile', 'navSettings'] },
];

const DEFAULT_SETTINGS = {
  showInlineHints:   false,
  showFloatingPanel: false,
};

// 組み込みプリセット（readonly）
const BUILTIN_PRESETS = [
  {
    id: 'default',
    name: 'デフォルト',
    readonly: true,
    bindings: { ...DEFAULT_KEYBINDINGS },
  },
  {
    id: 'vim',
    name: 'Vim 風',
    readonly: true,
    bindings: {
      focusNext:    'j',
      focusPrev:    'k',
      openPost:     'o',
      like:         'l',
      repost:       'r',
      quoteRepost:  'q',
      bookmark:     'b',
      reply:        '@',
      openProfile:  'p',
      openQuoted:   'o',
      newPost:      'n',
      focusSearch:  '/',
      toggleHelp:   '?',
      navHome:      'gh',
      navSearch:    'gs',
      navNotif:     'gn',
      navMessages:  'gm',
      navBookmarks: 'gb',
      navProfile:   'gp',
      navSettings:  'gS',
      tabPrev:      '[',
      tabNext:      ']',
      tabOuterPrev: '{',
      tabOuterNext: '}',
    },
  },
  {
    id: 'twitter',
    name: 'Twitter / X 風',
    readonly: true,
    bindings: {
      focusNext:    'j',
      focusPrev:    'k',
      openPost:     'Enter',
      like:         'l',
      repost:       'r',
      quoteRepost:  'q',
      bookmark:     'b',
      reply:        '@',
      openProfile:  'p',
      openQuoted:   'o',
      newPost:      'n',
      focusSearch:  '/',
      toggleHelp:   '?',
      navHome:      'gh',
      navSearch:    'gs',
      navNotif:     'gn',
      navMessages:  'gm',
      navBookmarks: 'gb',
      navProfile:   'gp',
      navSettings:  'gS',
      tabPrev:      '[',
      tabNext:      ']',
      tabOuterPrev: '{',
      tabOuterNext: '}',
    },
  },
  {
    id: 'claude',
    name: '最強 (Claude)',
    readonly: true,
    bindings: {
      focusNext:    'j',
      focusPrev:    'k',
      openPost:     'Enter',
      like:         'f',      // favorite — 人差し指ホームポジション
      repost:       'r',
      quoteRepost:  'e',      // express — q より直感的
      bookmark:     'b',
      reply:        '@',
      openProfile:  'p',
      openQuoted:   'o',
      newPost:      'n',
      focusSearch:  '/',
      toggleHelp:   '?',
      tabPrev:      '[',
      tabNext:      ']',
      tabOuterPrev: '{',
      tabOuterNext: '}',
      navHome:      'gh',
      navSearch:    'gs',
      navNotif:     'gn',
      navMessages:  'gm',
      navBookmarks: 'gb',
      navProfile:   'gp',
      navSettings:  'gS',
    },
  },
];
